# Generated by Django 3.2.9 on 2022-04-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
